### PR TITLE
Use same config for max_in_connections (pre and post handshake)

### PR DESCRIPTION
**Pull request by litchipi**
Related to https://github.com/massalabs/massa/pull/4116

### CODE REVIEW

**Review by AurelienFT — COMMENTED** [review]
Is it necessary to pass `allow_local_peers` to peernet ? As peernet don't do any check on the local ips/global etc ?

**Comment by litchipi** [comment]
@modship Added you for a review as Aurelien is unavailable
@damip If you have some time also, to ensure I fixed the issue as intented.

I ping you because the underlying issue https://github.com/massalabs/massa/issues/4035 is `p1`, so the sooner the better

**Review by modship — APPROVED** [review]

**Comment by damip** [comment]
> @modship Added you for a review as Aurelien is unavailable @damip If you have some time also, to ensure I fixed the issue as intented.
> 
> I ping you because the underlying issue [massalabs/massa#4035](https://github.com/massalabs/massa/issues/4035) is `p1`, so the sooner the better

So adding the local addr acceptance boolean will be done as a followup of this PR ?

**Comment by litchipi** [comment]
Actually this was just a mistake, PeerNet doesn't need to be aware if the peer is local or not, this is done on the side of massa.

**Comment by damip** [comment]
Then this is ok for me

**Pull request merged**
